# Generated by Django 2.0.6 on 2020-06-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('broadcast', models.CharField(max_length=20, null=True)),
                ('chapter_count', models.IntegerField(default=0, null=True)),
                ('content', models.TextField(null=True)),
                ('score', models.SmallIntegerField(default=5)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('img_src', models.ImageField(upload_to='img')),
            ],
            options={
                'db_table': 'album',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url', models.FileField(upload_to='video')),
                ('time_long', models.SmallIntegerField(null=True)),
                ('album_id', models.IntegerField()),
            ],
            options={
                'db_table': 'chapter',
            },
        ),
    ]
