# Generated by Django 2.0.6 on 2020-05-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('up_time', models.DateTimeField(auto_now_add=True)),
                ('pic', models.ImageField(upload_to='img')),
            ],
        ),
    ]
