# Generated by Django 2.0.6 on 2020-06-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('religions_name', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=40)),
                ('salt', models.CharField(max_length=40)),
                ('status', models.BooleanField(default=True)),
                ('img_src', models.ImageField(null=True, upload_to='user_html')),
                ('last_login_time', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(null=True)),
                ('address', models.CharField(max_length=40, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('register_time', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
